**資料型態**

In [ ]:
# 數值型態
integer_number = 5
float_number = 5.0
# 布林型態
boolean_number = True
# 字串型態
word = "This is a string"
# 容器型態
list_of_items = [integer_number, float_number, boolean_number, word]

In [ ]:
# type() 使用
print(type(integer_number))
print(type(float_number))
print(type(boolean_number))
print(type(word))
print(type(list_of_items))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>
<class 'list'>


**數學運算子**


In [ ]:
x = 20
y = 50
# 加法
print("x+y=", x+y)
# 減法
print("x-y=", x-y)
# 乘法
print("x*y=", x*y)
# 除法
print("x/y=", x/y) 
print("y/x=", y/x)
# 取餘數
print("y 除以 x 的餘數是：", y%x)
# 整除
print("y 除以 x 的商是：", y//x)


x+y= 70
x-y= -30
x*y= 1000
x/y= 0.4
y/x= 2.5
y 除以 x 的餘數是： 10
y除以 x 的商是： 2


**關係運算子**

In [ ]:
x = 5
y = 7
print("x > y ? ", x>y)
print("x < y ? ", x<y)
print("x == y ? ", x == y)
print("x >= y ? ", x >= y)
print("x <= y ? ", x <= y)


x > y ?  False
x < y ?  True
x == y ?  False
x >= y ?  False
x <= y ?  True


In [ ]:
x = 100
x == 50

True

**等號運算子**

In [ ]:
a = 50 
b = 2
# a+=b 等同於 a=a+b
a += b
print("a + b = ", a)

a + b =  52


In [ ]:
a = 50 
b = 2
# a-=b 等同於 a=a-b
a -= b
print("a - b = ", a)

a - b =  48


In [ ]:
a = 50 
b = 2
# a*=b 等同於 a=a*b
a *= b
print("a * b = ", a)

a * b =  100


In [ ]:
a = 50 
b = 2
# a/=b 等同於 a=a/b
a /= b
print("a / b = ", a)

a / b =  25.0


**邏輯運算子**

In [ ]:
x = True
y = False

# 在 python 裡面直接使用 and or not 來表示邏輯運算子
# x and y
print("x and y = ", x and y)

# x or y
print("x or y = ", x or y)

# not y
print("not y = ", not y)

x and y =  False
x or y =  True
not y =  True


**條件敘述**

**if 的使用**
```
if condition:
  excute
```



In [ ]:
if True:
  print("進入到 if 判斷式裡面啦！")
if False:
  print("如果你看到我就奇怪囉！！")

進入到 if 判斷式裡面啦！


In [ ]:
# 根據輸入判斷
grade = int(input("請跟我說這學期的電腦課分數："))
if grade >= 90:
  print("你非常優秀！")

請跟我說這學期的電腦課分數：90
你非常優秀！


**if / else 的使用**
```
if condition:
  excute
else:
  excute
```



In [ ]:
# 根據輸入判斷
grade = int(input("請跟我說這學期的電腦課分數："))
if grade >= 90:
  print("你非常優秀！")
else:
  print("再接再厲！！！")

請跟我說這學期的電腦課分數：85
再接再厲！！！


**if / elif/ else 的使用**
```
if condition:
  excute
elif condition:
  excute
else:
  excute
```

In [ ]:
# 根據輸入判斷
grade = int(input("請跟我說這學期的電腦課分數："))
if grade >= 90:
  print("你非常優秀！")
elif grade >= 60:
  print("有及格也很不錯！")
else:
  print("再接再厲！！！")

請跟我說這學期的電腦課分數：55
再接再厲！！！


**巢狀 if 條件敘述**
```
if condition:
  if condition:
    excute
  else:
    excute
else:
  if condition:
    excute
  elif condition:
    excute
```

In [ ]:
#  根據輸入判斷
grade = int(input("請跟我說這學期的電腦課分數："))
if grade >= 100:
  if grade > 100:
    print("超過 100 分 ？！想騙誰 ？")
  elif grade == 100:
    print("你是滿分天才！")
else:
  if grade >= 90:
    print("你非常優秀！")
  elif grade >= 60:
    print("有及格也很不錯！")
  else:
    print("再接再厲！！！")

請跟我說這學期的電腦課分數：60
有及格也很不錯！


**三元運算子**
```
True if condition else False
```

In [ ]:
#  根據輸入判斷
grade = int(input("請跟我說這學期的電腦課分數："))
if grade > 100:
  print("超過 100 分 ？！想騙誰 ？")
else:
  print("你在電腦課程裡%s一個滿分天才%s" % ("是" if grade == 100 else "還不是", "!!!" if grade == 100 else ", 再接再厲吧"))

請跟我說這學期的電腦課分數：90
你在電腦課程裡還不是一個滿分天才, 再接再厲吧


**迴圈介紹**

`range(start, stop, step)`
return [start, stop)

**for loop**


```
for variable in iterable:
  excute
```



In [ ]:
data = range(1, 11, 1)
print(type(data))
print(data)
for d in data:
  print(d)

In [ ]:
for d in range(1, 11, 1):
  print(d)

In [ ]:
list_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(type(list_data))
for d in list_data:
  print(d)

In [ ]:
tuple_data = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(type(tuple_data))
for d in tuple_data:
  print(d)

In [ ]:
dict_data = {'First name': "王", 'Last name': "小明"}
print(type(dict_data))
for key, name in dict_data.items():
  print("%s is %s" % (key, name))

<class 'dict'>
First name is 王
Last name is 小明


In [ ]:
set_data = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
print(type(set_data))
for d in set_data:
  print(d)

**break / continue**


```
for i in sequence:
  if condition:
    break / continue
```



In [ ]:
# 印出成績清單中及格的分數
grade_list = [50, 40, 70, 80, 120, 90, 30, 100, 60, 110]
for grade in grade_list:
  if grade < 60:
    continue
  else:
    print(grade)

In [ ]:
# 印出成績清單中及格的分數
# 但遇到超過 100 分的成績則停止並印出錯誤訊息
grade_list = [50, 40, 70, 80, 120, 90, 30, 100, 60, 110]
for grade in grade_list:
  if grade > 100:
    print("這份成績單怪怪的喔, 有超過一百分的成績")
    break
  if grade < 60:
    continue
  else:
    print(grade)

**while loop**


```
while condition:
  excute
```



In [ ]:
# 加總 1 ~ 10
# for loop
sum = 0 
for i in range(1, 11, 1):
  sum = sum + i
print("加總 1 ~ 10 = %d" % (sum))

加總 1 ~ 10 = 55


In [ ]:
# 加總 1 ~ 10
# while loop
sum = 0
i = 1 
while i <= 10:
  sum = sum + i
  i = i + 1
print("加總 1 ~ 10 = %d" % (sum))

加總 1 ~ 10 = 55


In [ ]:
# 加總 1 ~ 10
# while loop
sum = 0
i = 1 
while True:
  if i > 10:
    break
  sum = sum + i
  i = i + 1
print("加總 1 ~ 10 = %d" % (sum))

加總 1 ~ 10 = 55


**巢狀迴圈**


```
for variable in iterable:
  ...
  for variable in iterable:
    excute
  ...
```


```
while condition:
  ...
  while condition:
    excute
  ...

```

In [ ]:
# 利用雙層迴圈印出 21 ~ 40
# 限制 for 迴圈如下：
for i in range(1, 11, 1):
  for j in range(1, 11, 1):
    # 如何實作？
    continue

In [ ]:
# 利用雙層迴圈印出 21 ~ 40
# 限制 for 迴圈如下：
for i in range(1, 11, 1):
  if i < 2:
      continue
  if i == 4:
    break
  for j in range(1, 11, 1):
    print(10*i+j) 

21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40


In [ ]:
# 利用雙層迴圈印出 21 ~ 40
# 限制 while 迴圈如下：
i = 1
j = 1
while True:
  while True:
    # 如何實作？
    continue

In [ ]:
# 利用雙層迴圈印出 21 ~ 40
# 限制 while 迴圈如下：
i = 1
j = 1
while True:
  i = i + 1
  if i < 2:
    continue
  if i == 4:
    break
  while True:
    print(10*i+j)
    if j == 10:
      j = 1
      break
    j = j + 1
    continue

21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40


**Function**

In [ ]:
def max(a, b):
  return a if a > b else b

In [ ]:
max_number = max(3, 5)
print(max_number)

5


In [ ]:
sum1to10 = 0
for i in range(1, 11):
  sum1to10 += i

sum1to100 = 0
for i in range(1, 101):
  sum1to100 += i

print(sum1to10)
print(sum1to100)

55
5050


In [ ]:
def sumAtoB(a, b):
  sum = 0
  for i in range(a, b+1):
    sum += i
  return sum

sum1to10 = sumAtoB(1, 10)
sum1to100 = sumAtoB(1, 100)
print(sum1to10)
print(sum1to100)

55
5050


**類別**

In [ ]:
class Animal():
  def __init__(self, name):
      self.name = name

a = Animal("common animal")
print(a.name)

common animal


In [ ]:
class Dog(Animal):
  def __init__(self, name):
    super().__init__('Dog:'+name)

a = Animal("common animal")
print(a.name)
b = Dog('Andy')
print(b.name)

common animal
Dog:Andy


In [ ]:
class Animal():
  def __init__(self, name):
    self.name = name
  def sound(self):
    return "not special."
 
class Dog(Animal):
  def __init__(self, name):
    super().__init__('Dog: '+name)
  def sound(self):
    return "barking"

a = Animal("common animal")
print(a.name, "的叫聲：", a.sound())
b = Dog('Andy')
print(b.name, "的叫聲：", b.sound())

common animal 的叫聲： not special.
Dog: Andy 的叫聲： barking


**OPENCV,PIL**

In [20]:
!pip install Pillow
from PIL import Image as Image

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
from PIL import Image as Image

# 讀取 PIL image
pil_image = Image.open('lena.jpeg').convert('RGB')
print(pil_image.size)
print(pil_image.mode)
print(type(pil_image))

(316, 316)
RGB
<class 'PIL.Image.Image'>


In [23]:
import numpy as np

# convert to np array
img_np = np.array(pil_image)
print(img_np.shape)

(316, 316, 3)


In [ ]:
!pip install opencv-python
!pip install opencv-contrib-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
cd /content/sample_data

/content/sample_data


In [ ]:
import cv2

img = cv2.imread('lena.jpeg')
print(type(img))
print(img.shape)
print(img)

In [ ]:
import cv2
import numpy as np

grey_img = cv2.imread('lena.jpeg', 0)
print(type(grey_img))
print(grey_img.shape)
print(grey_img)
cv2.imwrite('grey_lena.jpeg', grey_img.astype(np.uint8))

<class 'numpy.ndarray'>
(316, 316)
[[162 162 162 ... 171 167 142]
 [162 162 162 ... 171 167 142]
 [162 162 162 ... 171 166 142]
 ...
 [ 51  49  51 ...  93  97  94]
 [ 44  47  51 ...  99 102 101]
 [ 44  51  53 ... 103 104 107]]


True

In [ ]:
import cv2

img = cv2.imread('lena.jpeg')
print(img.shape)
(image_b, image_g, image_r) = cv2.split(img)
print(image_b.shape)
print(image_g.shape)
print(image_r.shape)

(316, 316, 3)
(316, 316)
(316, 316)
(316, 316)


In [ ]:
merge_img = cv2.merge([image_b, image_g, image_r])
print(merge_img.shape)

(316, 316, 3)


In [18]:
import cv2

img = cv2.imread('lena.jpeg')
print(img.shape)
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray_img.shape)

(316, 316, 3)
(316, 316)


In [ ]:
import cv2
import numpy as np

img = np.ones([5,5])
print(img.shape)
cv2.imwrite('output.png', img.astype(np.uint8))

(5, 5)


True

In [ ]:
import cv2
import numpy as np

img = cv2.imread('lena.jpeg')
# 移動圖片位置 (Translation)
def translate(img, x, y):
 transMat = np.float32([[1,0,x],[0,1,y]])
 dimensions = (img.shape[1], img.shape[0])
 return cv2.warpAffine(img, transMat, dimensions)
# -x → 往左移動 ; x → 往右移動
# -y → 往上移動 ; y → 往下移動
translated = translate(img, -100, 100)
cv2.imwrite('translated_lena.jpeg', translated.astype(np.uint8))

True

In [ ]:
import cv2

img = cv2.imread('lena.jpeg')
def rotate(img, angle, rotPoint=None):
  (height,width) = img.shape[:2]
  if rotPoint is None:
    rotPoint = (width//2,height//2)
  rotMat = cv2.getRotationMatrix2D(rotPoint, angle, 1.0)
  dimensions = (width,height)
  return cv2.warpAffine(img, rotMat, dimensions)
# 輸入角度作為參數
rotated = rotate(img, -45)
cv2.imwrite('Rotated45_lena.jpeg', rotated.astype(np.uint8))

True

In [ ]:
import cv2

img = cv2.imread('lena.jpeg', 0)
print(img.shape)
resize_img = cv2.resize(img, (158, 158), interpolation=cv2.INTER_AREA)
print(resize_img.shape)
cv2.imwrite('resize_lena.jpeg', resize_img.astype(np.uint8))

(316, 316)
(158, 158)


True